apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: projet
  labels:
    app: "nginx"
spec:
  selector:
    matchLabels:
      app: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: "nginx"
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "projet-31:5000"
    spec:
      containers:
      - name : nginx
        image: "nginx:1.11.5"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        ports:
          - name: https
            containerPort: 443
            protocol: TCP
        resources:
          requests:
            memory: 100Mi
            cpu: 64m
          limits:
            memory: 100Mi
            cpu: 64m
        volumeMounts:
          - name: nginx
            mountPath: "/etc/nginx/conf.d"
          - name: tls-volume
            mountPath: /etc/nginx/ssl            
      volumes:
      - name: nginx
        configMap:
          name: nginx
      - name: tls-volume
        secret:
          secretName: nginx-tls
