apiVersion: v1
kind: Service
metadata:
 name: projet-31
 namespace: projet
 labels:
   app: "projet-31"
spec:
 ports:
 - port: 5000
   name: http
   targetPort: 5000
 selector:
   app: "projet-31"

---